# Generated by Django 2.2.6 on 2019-12-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('grasa_saturada', models.IntegerField()),
                ('otras_grasas', models.IntegerField()),
                ('azucar_total', models.IntegerField()),
                ('sodio', models.IntegerField()),
                ('energia', models.IntegerField()),
                ('energia_pporcion', models.IntegerField()),
                ('porcion', models.IntegerField()),
            ],
        ),
    ]
