# Generated by Django 2.2.6 on 2019-12-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='porcion',
        ),
        migrations.AddField(
            model_name='producto',
            name='porciones',
            field=models.IntegerField(default=0),
        ),
    ]
