# Generated by Django 2.2.6 on 2019-12-07 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gda', '0002_auto_20191206_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='energia_pporcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='porciones',
        ),
    ]
